name: lookup-package-url
description: Provides a container package's web page URL as an output to other actions.
inputs:
  token:
    description: Token to access the GitHub API with.
  owner:
    description: GitHub organization or user that owns the repository.
  repo:
    description: GitHub repository name.
  tag:
    description: The container package's tag from your Docker build step.
outputs:
  url:
    description: URL to the container package's web page on GitHub.
    value: ${{ steps.action.outputs.url }}
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: stable
    - shell: bash
      run: |
        go run ${GITHUB_ACTION_PATH}/main.go \
          -token "${{ inputs.token }}" \
          -owner "${{ inputs.owner }}" \
          -repo "${{ inputs.repo }}" \
          -tag "${{ inputs.tag }}"
      env:
        GH_TOKEN: ${{ github.token }}
