name: lookup-package-url
description: TODO
inputs:
  token:
    description: TODO
  owner:
    description: TODO
  repo:
    description: TODO
  tag:
    description: TODO
outputs:
  url:
    description: TODO
    value: ${{ steps.action.outputs.url }}
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: stable
    - shell: bash
      run: |
        go run ${{ github.action_path }} \
          -token "${{ inputs.token }}" \
          -owner "${{ inputs.owner }}" \
          -repo "${{ inputs.repo }}" \
          -tag "${{ inputs.tag }}"
      env:
        GH_TOKEN: ${{ github.token }}
